# Generated by Django 5.2.3 on 2025-06-14 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_usedingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedingredients',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Используемое количество'),
        ),
    ]
